name: wike # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
#version: '1.8.1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: wike
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
layout:
  /usr/share/wike:
    symlink: $SNAP/usr/share/wike
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1/WebKitNetworkProcess:
    bind-file: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1/WebKitNetworkProcess
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1/WebKitWebProcess:
    bind-file: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitWebProcess
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so:
    bind-file: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so

slots:
  wike:
    interface: dbus
    bus: session
    name: com.github.hugolabe.Wike
    
parts:
  wike:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/hugolabe/Wike.git
    source-tag: '1.8.3'
    stage-packages:
      - python3-dbus
      - python3-requests     
    meson-parameters:
      - --prefix=/usr
    override-prime: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i usr/bin/wike
      rm -rf usr/share/man
      rm -rf usr/share/doc
    parse-info: [ usr/share/metainfo/com.github.hugolabe.Wike.metainfo.xml ]
apps:
  wike:
    command: usr/bin/wike
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - process-control
      - unity7
      - audio-playback
      - network
      - network-status
    common-id: com.github.hugolabe.Wike
    desktop: usr/share/applications/com.github.hugolabe.Wike.desktop
