name: color-code # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: color-code
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64


slots:
  wike:
    interface: dbus
    bus: session
    name: com.oyajun.ColorCode

parts:
  wike:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/oyajun/color-code.git
    source-tag: 'v0.1.0'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/color-code/current/usr
    stage-packages:
      - python3-dbus
    parse-info: [ usr/share/metainfo/com.oyajun.ColorCode.metainfo.xml ]
    organize:
      usr/local: usr
      snap/color-code/current: .
      usr/lib/python3: usr/lib/python3.10

apps:
  color-code:
    command: usr/bin/color-code
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/usr/lib/python3.10/dist-packages:$PYTHONPATH
    plugs:
      - unity7
    common-id: com.oyajun.ColorCode

